# Generated by Django 3.1.2 on 2020-11-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0002_artikelmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikelmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=12, null=True),
        ),
    ]
