# Generated by Django 3.1.2 on 2020-11-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0003_auto_20201127_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikelmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
