# Generated by Django 3.1.2 on 2020-11-28 12:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0004_auto_20201127_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikelmodel',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 12, 18, 45, 778182, tzinfo=utc)),
        ),
    ]
