# Generated by Django 3.1.2 on 2020-11-28 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0005_artikelmodel_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikelmodel',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='artikelmodel',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 20, 8, 16, 129016)),
        ),
    ]
