# Generated by Django 3.1.2 on 2020-11-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0007_auto_20201128_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikelmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
