# Generated by Django 3.1.2 on 2020-12-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0008_auto_20201130_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikelmodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
