# Generated by Django 3.1.2 on 2020-12-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0009_artikelmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikelmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artikel/'),
        ),
    ]
