# Generated by Django 3.1.2 on 2020-12-09 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0010_auto_20201203_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('create_data', models.DateTimeField(auto_now_add=True)),
                ('judul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='artikel.artikelmodel')),
            ],
        ),
    ]
