# Generated by Django 3.1.2 on 2020-12-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0011_commentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikelmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
