# Generated by Django 3.1.2 on 2020-12-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0013_commentmodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikelmodel',
            options={'ordering': ['-create_at', '-update_at']},
        ),
        migrations.AlterField(
            model_name='artikelmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=3, null=True, unique=True),
        ),
    ]
