# Generated by Django 3.1.2 on 2020-12-27 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0014_auto_20201227_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikelmodel',
            name='slug',
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=3, null=True, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artikel.artikelmodel')),
            ],
        ),
    ]
