# Generated by Django 3.1.2 on 2020-12-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0015_auto_20201227_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikelmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=3, null=True, unique=True),
        ),
    ]
