# Generated by Django 3.1.2 on 2020-12-27 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0016_artikelmodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='slug',
        ),
    ]
