# Generated by Django 3.1.2 on 2020-12-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0021_auto_20201228_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikelmodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, null=True, unique=True),
        ),
    ]
